apps/adopcion/urls.py
from django.conf.urls import url

from apps.adopcion.views import index, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^index$', index),
    url(r'^solicitud/listar$', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view(), name='solicitud_eliminar'),

]

refugio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/adopcion/models.py
from django.db import models


# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=70)
    email = models.CharField(max_length=70)
    domicilio = models.TextField(max_length=70)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos)

    def full_name(self):
        return self.nombre + ' ' + self.apellidos


class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona

        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'domicilio',
        ]

        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Aplleidos',
            'edad': 'Edad',
            'telefono': 'Telefono',
            'email': 'Correo',
            'domicilio': 'Direccion',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'edad': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.Textarea(attrs={'class': 'form-control'}),
        }


class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud

        fields = [
            'numero_mascotas',
            'razones',
        ]

        labels = {
            'numero_mascotas': 'Cantidad de Mascotas',
            'razones': 'Razones',
        }

        widgets = {
            'numero_mascotas': forms.TextInput(attrs = {'class': 'form-control'}),
            'razones': forms.Textarea(attrs = {'class': 'form-control'}),
        }

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.adopcion.models import Solicitud, Persona
from apps.adopcion.forms import PersonaForm, SolicitudForm


def index(request):
    return HttpResponse("Soy la pagina principal de la app adopcion")


class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'


class SolicitudCreate(CreateView):
    model = Solicitud
    form_class = SolicitudForm
    second_form_class = PersonaForm
    template_name = 'adopcion/solicitud_form.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))


class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)

        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)

        form = self.form_class(request.POST, instance=solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)

        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())


class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    <h3>Desea eliminar la solicitud de {{ object.persona.full_name }}</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <hr/>
    <a class="btn btn-default" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>

</form>
{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}

    {{ form2.as_p }}
    {{ form.as_p }}

    <!--div class="row">
        <div class="form-group">
            <label for="{{form2.nombre.name}}">{{ form2.nombre.label }}</label>
            {{ form2.nombre }}
        </div>
    </div-->

    <button type="submit">Guardar</button>

</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Nro. Solicitud</td>
            <td>Adoptante</td>
            <td>Nro. Mascotas</td>
            <td>Razones</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for solicitud in object_list %}
                <tr>
                    <td>{{ solicitud.id }}</td>
                    <td>{{ solicitud.persona.full_name }}</td>
                    <td>{{ solicitud.numero_mascotas }}</td>
                    <td>{{ solicitud.razones }}</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No Hay Registros de Solicitudes</h1>
        {% endif %}
    </tbody>
</table>

{% endblock %}