apps/mascota/urls.py
from django.conf.urls import url

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),
]

refugio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):

    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null = True, blank = True, on_delete = models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank = True)

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad Aproximada',
            'fecha_rescate': 'Fecha de Rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }

        widgets = {
            'nombre': forms.TextInput(attrs = {'class': 'form-control'}),
            'sexo': forms.TextInput(attrs = {'class': 'form-control'}),
            'edad_aproximada': forms.TextInput(attrs = {'class': 'form-control'}),
            'fecha_rescate': forms.TextInput(attrs = {'class': 'form-control'}),
            'persona': forms.Select(attrs = {'class': 'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota


def index(request):
    return render(request, 'mascota/index.html')


def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_lsitar')
    else:
        form = MascotaForm()

    return render(request, 'mascota/mascota_form.html', {'form': form})


def mascota_list(request):
    mascotas = Mascota.objects.all();
    contexto = {'mascotas': mascotas}

    return render(request, 'mascota/mascota_list.html', contexto)


def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'form': form})


def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota': mascota})


class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'


class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %}
App Mascota

{% endblock %}

{% block content %}

<h5>Soy el contenido de mascota</h5>

{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    <h3>Desea eliminar el registro de {{ object.nombre }}</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <hr/>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>

</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>

</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for mascota in object_list %}
                <tr>
                    <td>{{ mascota.id }}</td>
                    <td>{{ mascota.nombre }}</td>
                    <td>{{ mascota.sexo }}</td>
                    <td>{{ mascota.edad_aproximada }}</td>
                    <td>{{ mascota.fecha_rescate }}</td>
                    <td>{{ mascota.persona.full_name }}</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No Hay Registros de Mascotas</h1>
        {% endif %}
    </tbody>
</table>

{% endblock %}